### ISSUE TITLE
Return err instead of panicking

### ISSUE THREAD

**Issue by mholt** [sarnowski/mitigation#3]
How would you feel about a PR that replaces panics with a `return err`? It would be nice not to have to use recover() and stuff; personally I'd rather just handle the error.

**Comment by sarnowski** [comment]
I thought about it when I wrote the library. Using panic() is not very idiomatic but I feel it is the right usage for it. The problem is that there are various actions that cannot be undone. This means, that your application state may be inconsistent and unrecoverable if an error occurs. I added the CanActivate() function for exactly this reason - being able to check wether the Activate() function will work or not. I think the CanActivate() function can be improved by checking if the given user and group id exist for example.

What is your use case when an error happens? What do you do when recovering the panics?

**Comment by mholt** [comment]
I actually haven't begun using the package yet; just gave it a once-over to see if it'll meet my needs. (Looks like there's lots of tricky system-level stuff. I'm still looking into that related to what I need to do.) If I did use deescalation, it would be at program start, and I would just print a nicer error message than a stack trace, and then exit.

Your explanation makes sense though. In that case, CanActivate() should be as good a predictor as possible. I'll submit a PR along what you suggested if I 1) end up using this package and 2) feel confident in my ability to make that change correctly. ;)

Thanks for this well-documented little package! :+1:
